fix: Extract syntax path only from Syntax object
For some reason, passing Syntax object is not working:

```
>>> view.assign_syntax(sublime.find_syntax_by_name('JSON'))
Traceback (most recent call last):
  File "__main__", line 1, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime.py", line 1630, in assign_syntax
    sublime_api.view_assign_syntax(self.view_id, syntax)
TypeError: String required
>>> view.assign_syntax(sublime.find_syntax_by_name('JSON')[0])
```

https://forum.sublimetext.com/t/view-assign-syntax-do-not-accept-syntax-object/61271